# Generated by Django 4.0.2 on 2022-02-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=60)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('image_url', models.URLField(max_length=300)),
            ],
        ),
    ]
