# Generated by Django 4.0.2 on 2022-02-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_slot_professional_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='experience',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='field',
            field=models.CharField(default='Counselling Psychologist', max_length=100),
            preserve_default=False,
        ),
    ]
